# Generated by Django 2.0.7 on 2018-11-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20181024_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='token',
            field=models.CharField(default='empty', max_length=20),
            preserve_default=False,
        ),
    ]
