# Generated by Django 2.0.7 on 2018-11-21 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_visitor_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=1)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Staff')),
            ],
        ),
    ]
