# Generated by Django 2.0.7 on 2018-11-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_requests_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='staff',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_status',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
