# Generated by Django 2.0.7 on 2018-11-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20181125_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=500)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visit_status',
        ),
        migrations.AddField(
            model_name='requests',
            name='visitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Visitor'),
        ),
    ]
