# Generated by Django 2.0.7 on 2018-11-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20181126_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='comment',
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
