# Generated by Django 2.0.7 on 2018-11-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20181126_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='visitor_name',
            new_name='visitor',
        ),
    ]
